const getRandomElement = (arr) => arr[Math.floor(Math.random() * arr.length)];

// From your job_title.csv 'name' column, which are the translation keys
const jobTitleKeys = [
  "jobTitle.mimarlarVeMuhendisler",
  "jobTitle.elektrikciler",
  "jobTitle.tesisatcilar",
  "jobTitle.boyacilarVeSivacilar",
  "jobTitle.zeminDosemeUstalari",
  "jobTitle.icDekorasyonUstalari",
  "jobTitle.peyzajMimariVeBahcivanlar",
  "jobTitle.insaatYoneticileriVeDenetciler",
  "jobTitle.bakimVeOnarimEkipleri",
  "jobTitle.insaatIscileriVeUstalar",
  "jobTitle.catiUstalari"
];

const sampleSkills = [
  "Proje Yönetimi", "CAD Tasarımı", "Elektrik Tesisatı", "Sıhhi Tesisat Onarımı", "İç Cephe Boyama",
  "Zemin Döşeme", "Müşteri Hizmetleri", "Problem Çözme", "Ekip Liderliği", "Bütçeleme",
  "Peyzaj Tasarımı", "İnşaat Denetimi", "Çatı Kaplama", "Tadilat", "Bakım ve Onarım",
  "Stripe Entegrasyonu", "API Geliştirme"
];

const sampleLocations = ["İstanbul, TR", "Ankara, TR", "İzmir, TR", "Bursa, TR", "Antalya, TR", "Berlin, DE", "Amsterdam, NL", "Köln, DE"];

const placeholderImageBase = "https://i.pravatar.cc/150?u="; // Simple placeholder

const generateRandomString = (length) => {
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';
  for (let i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * characters.length));
  }
  return result;
};


export const mockExperts = [
  {
    id: "expert-uuid-1",
    name: "Ayşe",
    surname: "Yılmaz",
    fullName: "Ayşe Yılmaz", // Derived: name + surname
    email: "ayse.yilmaz@example.com",
    phoneNumber: "+90 555 123 4567",
    profileImage: `${placeholderImageBase}ayse_yilmaz`, // Maps to profileImageUrl in ExpertPage
    profileImageUrl: `${placeholderImageBase}ayse_yilmaz`, // Explicitly for ExpertPage if preferred
    address: "Gülbahar Mah. Cemal Sururi Sk. No:15",
    postCode: "34394",
    role: "EXPERT", // from Role enum
    jobTitle: getRandomElement(jobTitleKeys), // This is the translation key
    companyName: "Yılmaz Mimarlık Ltd.",
    chamberOfCommerceNumber: "TR12345678",
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 5000).toFixed(2),
    accountBlocked: false,
    // Fields used by ExpertPage.jsx that might not be direct entity fields but part of a DTO:
    bio: "Deneyimli bir mimar olarak, yenilikçi ve sürdürülebilir çözümler sunuyorum. Projelerinizi hayata geçirmek için buradayım.",
    skills: [sampleSkills[0], sampleSkills[1], sampleSkills[9]],
    location: "Şişli, İstanbul", // Simplified location for display
  },
  {
    id: "expert-uuid-2",
    name: "Mehmet",
    surname: "Kaya",
    fullName: "Mehmet Kaya",
    email: "mehmet.kaya@example.com",
    phoneNumber: "+90 555 234 5678",
    profileImage: `${placeholderImageBase}mehmet_kaya`,
    profileImageUrl: `${placeholderImageBase}mehmet_kaya`,
    address: "Atatürk Cad. No: 101",
    postCode: "06500",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: "Kaya Elektrik Hizmetleri",
    chamberOfCommerceNumber: null, // Can be optional
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 3000).toFixed(2),
    accountBlocked: false,
    bio: "Elektrik tesisatı ve arıza giderme konusunda 10+ yıl deneyimli uzmanım. Güvenli ve kaliteli işçilik prensibimdir.",
    skills: [sampleSkills[2], sampleSkills[7], "Akıllı Ev Sistemleri"],
    location: "Çankaya, Ankara",
  },
  {
    id: "expert-uuid-3",
    name: "Fatma",
    surname: "Demir",
    fullName: "Fatma Demir",
    email: "fatma.demir@example.com",
    phoneNumber: "+90 555 345 6789",
    profileImage: `${placeholderImageBase}fatma_demir`,
    profileImageUrl: `${placeholderImageBase}fatma_demir`,
    address: "İnönü Bulvarı, No:55",
    postCode: "35200",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: null,
    chamberOfCommerceNumber: null,
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 1500).toFixed(2),
    accountBlocked: true, // Example of a blocked account
    bio: "Her türlü sıhhi tesisat işlerinizde (su, doğalgaz) güvenilir ve hızlı çözümler sunan tecrübeli bir ustayım.",
    skills: [sampleSkills[3], "Doğalgaz Tesisatı", "Kombi Bakımı"],
    location: "Konak, İzmir",
  },
  {
    id: "expert-uuid-4",
    name: "John",
    surname: "Doe",
    fullName: "John Doe",
    email: "john.doe@example.com",
    phoneNumber: "+49 177 1234567",
    profileImage: `${placeholderImageBase}john_doe`,
    profileImageUrl: `${placeholderImageBase}john_doe`,
    address: "Hauptstrasse 10",
    postCode: "10115",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: "Doe Renovations GmbH",
    chamberOfCommerceNumber: "DE98765432",
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 7000).toFixed(2),
    accountBlocked: false,
    bio: "Experienced painter and plasterer dedicated to transforming spaces with precision and artistry. Customer satisfaction is my priority.",
    skills: [sampleSkills[4], "Dış Cephe Boyama", "Duvar Kağıdı Uygulama"],
    location: "Mitte, Berlin",
  },
  {
    id: "expert-uuid-5",
    name: "Maria",
    surname: "Garcia",
    fullName: "Maria Garcia",
    email: "maria.garcia@example.com",
    phoneNumber: "+34 600 123 456",
    profileImage: `${placeholderImageBase}maria_garcia`,
    profileImageUrl: `${placeholderImageBase}maria_garcia`,
    address: "Calle Mayor 50",
    postCode: "28013",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: "Garcia Interiors",
    chamberOfCommerceNumber: "ESB12345678",
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 4200).toFixed(2),
    accountBlocked: false,
    bio: "Creative interior decorator with a passion for creating beautiful and functional living environments. Let's design your dream space!",
    skills: [sampleSkills[5], "Mekan Planlama", "Renk Teorisi", "Mobilya Seçimi"],
    location: "Centro, Madrid",
  },
  // Add 7 more experts to reach 12
  {
    id: "expert-uuid-6",
    name: "Ali",
    surname: "Veli",
    fullName: "Ali Veli",
    email: "ali.veli@example.com",
    phoneNumber: "+90 555 456 1234",
    profileImage: `${placeholderImageBase}ali_veli`,
    profileImageUrl: `${placeholderImageBase}ali_veli`,
    address: "Bahariye Cad. No: 49",
    postCode: "34710",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: "Veli Peyzaj",
    chamberOfCommerceNumber: "TR98765001",
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 2200).toFixed(2),
    accountBlocked: false,
    bio: "Bahçe ve peyzaj düzenleme konusunda uzmanlaşmış, doğayla iç içe tasarımlar sunan bir profesyonelim.",
    skills: [sampleSkills[10], "Sulama Sistemleri", "Bitki Bakımı"],
    location: "Kadıköy, İstanbul",
  },
  {
    id: "expert-uuid-7",
    name: "Sophie",
    surname: "Bernard",
    fullName: "Sophie Bernard",
    email: "sophie.bernard@example.com",
    phoneNumber: "+33 1 4567 8901",
    profileImage: `${placeholderImageBase}sophie_bernard`,
    profileImageUrl: `${placeholderImageBase}sophie_bernard`,
    address: "Rue de Rivoli 100",
    postCode: "75001",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: "Bernard Construction",
    chamberOfCommerceNumber: "FR123987456",
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 10000).toFixed(2),
    accountBlocked: false,
    bio: "Large scale construction project manager with 15 years of experience in overseeing complex builds from start to finish.",
    skills: [sampleSkills[0], sampleSkills[11], "Risk Yönetimi"],
    location: "1st Arr., Paris",
  },
  {
    id: "expert-uuid-8",
    name: "Kenan",
    surname: "Işık",
    fullName: "Kenan Işık",
    email: "kenan.isik@example.com",
    phoneNumber: "+90 555 789 4561",
    profileImage: `${placeholderImageBase}kenan_isik`,
    profileImageUrl: `${placeholderImageBase}kenan_isik`,
    address: "Fevzi Çakmak Bul. No: 22",
    postCode: "16050",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: "Işık Çatı Sistemleri",
    chamberOfCommerceNumber: "TR16000123",
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 3300).toFixed(2),
    accountBlocked: false,
    bio: "Çatı aktarma, izolasyon ve onarım konularında uzmanım. Kaliteli malzeme ve garantili işçilik sunuyorum.",
    skills: [sampleSkills[12], "Kiremit Çatı", "Membran Uygulama"],
    location: "Osmangazi, Bursa",
  },
  {
    id: "expert-uuid-9",
    name: "Laura",
    surname: "Schmidt",
    fullName: "Laura Schmidt",
    email: "laura.schmidt@example.com",
    phoneNumber: "+49 178 9012345",
    profileImage: `${placeholderImageBase}laura_schmidt`,
    profileImageUrl: `${placeholderImageBase}laura_schmidt`,
    address: "Hohe Str. 50",
    postCode: "50667",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    bio: "Meticulous flooring expert specializing in hardwood, laminate, and luxury vinyl. Transforming floors with precision.",
    skills: [sampleSkills[5], "Parke Döşeme", "Zemin Hazırlığı"],
    location: "Innenstadt, Köln",
  },
  {
    id: "expert-uuid-10",
    name: "Emre",
    surname: "Şahin",
    fullName: "Emre Şahin",
    email: "emre.sahin@example.com",
    phoneNumber: "+90 555 111 2233",
    profileImage: `${placeholderImageBase}emre_sahin`,
    profileImageUrl: `${placeholderImageBase}emre_sahin`,
    address: "Kazım Dirik Mah. 187 Sk. No:4",
    postCode: "07070",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: "Şahin Teknik Servis",
    chamberOfCommerceNumber: "TR07009876",
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 1200).toFixed(2),
    accountBlocked: false,
    bio: "Ev aletleri tamiri ve genel bakım hizmetleri. Hızlı, güvenilir ve uygun fiyatlı servis.",
    skills: [sampleSkills[14], "Beyaz Eşya Tamiri", "Küçük Ev Aletleri"],
    location: "Konyaaltı, Antalya",
  },
  {
    id: "expert-uuid-11",
    name: "Anna",
    surname: "Kowalski",
    fullName: "Anna Kowalski",
    email: "anna.kowalski@example.com",
    phoneNumber: "+48 500 123 456",
    profileImage: `${placeholderImageBase}anna_kowalski`,
    profileImageUrl: `${placeholderImageBase}anna_kowalski`,
    address: "ul. Marszałkowska 1",
    postCode: "00-001",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: "Kowalski Architekci",
    chamberOfCommerceNumber: "PL1234567890",
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 6000).toFixed(2),
    accountBlocked: false,
    bio: "Architect with a focus on modern residential and commercial design. Bringing visions to life through innovative architecture.",
    skills: [sampleSkills[1], "Sürdürülebilir Tasarım", "3D Modelleme"],
    location: "Śródmieście, Warsaw",
  },
  {
    id: "expert-uuid-12",
    name: "Hans",
    surname: "Van Dijk",
    fullName: "Hans Van Dijk",
    email: "hans.vandijk@example.com",
    phoneNumber: "+31 6 87654321",
    profileImage: `${placeholderImageBase}hans_vandijk`,
    profileImageUrl: `${placeholderImageBase}hans_vandijk`,
    address: "Keizersgracht 123",
    postCode: "1015 CJ",
    role: "EXPERT",
    jobTitle: getRandomElement(jobTitleKeys),
    companyName: "Van Dijk Totaalonderhoud",
    chamberOfCommerceNumber: "NL09876543B01",
    stripeCustomerId: `cus_${generateRandomString(14)}`,
    balance: (Math.random() * 2500).toFixed(2),
    accountBlocked: false,
    bio: "All-round maintenance and repair expert. No job too small, ensuring your property is always in top condition.",
    skills: [sampleSkills[14], "Genel Tamirat", "Marangozluk"],
    location: "Centrum, Amsterdam",
  }
];